### ISSUE TITLE
Question: 0.11.0

### ISSUE THREAD

**Issue by 20kano** [floooh/sokol-zig#38]
There is no `log.zig` in the zig-0.11.0 branch, is this intentional?

**Comment by floooh** [comment]
Not intentional, but a side effect that the 0.11.0 branch was created before sokol_log.h existed (and the automatic binding generation only updates the main branch with the 0.10.0 compatible code generation).

If zig 0.11.0 is still far away it will probably make sense to merge main into 0.11.0 from time to time, this needs to be done manually though.

**Comment by floooh** [comment]
PS: I have updated the zig-0.11.0 branch with the current state of master.
