### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by SimonLSchlee** [floooh/sokol-zig#75]
It would be good to add a LICENSE file, so it is clear how this code can be used.

I was thinking about maybe pulling out the emsdk setup code into a separate dependency, so that the emsdk code can be reused with other projects, but stopped because of missing license info.

**Comment by floooh** [comment]
Good point, I copied the LICENSE file from the sokol repo (which is zlib/png, slightly more permissive than MIT since no attribution is required).

Thanks for writing the issue!

**Comment by floooh** [comment]
Btw, the emsdk setup code is currently a bit half-assed since the actual SDK is downloaded into the global Zig cache, but without any ability to 'manage' the Emscripten SDK (e.g. updating to a more recent version, or uninstalling).

An improved Emscripten SDK integration with the Zig build system is probably a hole project on its own.
